server_config:
  map_folder:            "/tmp/maplab_server_map"
  resource_folder:       ""
  map_backup_interval_s: 120

  submap_commands:
    - "optvi --ba_num_iterations=10 --ba_enable_signal_handler=false --ba_hide_iterations_console_output=true"
    - "elq"

  global_map_commands:
    - "aam"
    - "lc"
    - "optvi --ba_num_iterations 1 --ba_enable_signal_handler=false --ba_hide_iterations_console_output=true"
    - "elq --vi_map_landmark_quality_min_observers=2"
    - "visualize_xyzi_pointclouds --vis_pointcloud_accumulated_before_publishing --vis_pointcloud_color_random"

connection_config:
  - name:                lidarstick
    topic:               "/maplab_node/map_update_notification"
    ip:                  "lidarstick"
    user:                "lidarstick"
